name: 🔍 Check Formatting

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Enable Debugging

jobs:
  check-coding-style:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/viennatools/vienna-builder:vtk
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📋 Install Dependencies
        run: pip install -U cmakelang pyyaml

      - name: 🔍 Check Format
        run: |
          cmake -B build
          cmake --build build --target format-check
