name: 🔍 Check Formatting

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Enable Debugging

jobs:
  check-coding-style:
    runs-on: ubuntu-latest
    container: fedora:41

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🖥️ Setup Environment
        uses: ./.github/actions/setup
        with:
          container: ubuntu-latest
          install-vtk: true

      - name: 📋 Install Dependencies
        run: pip install -U cmakelang pyyaml && sudo dnf install tmate

      - name: 🐛 Debug Issues
        if: ${{ github.event.inputs.debug == 'true' }}
        uses: mxschmitt/action-tmate@v3
        with:
          install-dependencies: false
          limit-access-to-actor: true

      - name: 🔍 Check Format
        run: |
          cmake -B build
          cmake --build build --target format-check
