name: 🐍 Build Bindings

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  bindings:
    strategy:
      fail-fast: false

      matrix:
        vtk-system: [true, false]
        os: [ubuntu-latest, windows-latest, macos-latest]

        exclude:
          - os: macos-latest
            vtk-system: true

          - os: windows-latest
            vtk-system: true

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'fedora:38' || null }}

    name: '🐍 Build Bindings on ${{ matrix.os }} [VTK installed: "${{ matrix.vtk-system }}"]'

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🖥️ Setup Environment
        uses: ./.github/actions/setup
        with:
          container: ${{ matrix.os }}
          install-vtk: ${{ matrix.vtk-system }}

      - name: 🐍 Build Python Module
        run: pip3 install --user . -v
