name: 🐍 Build Bindings

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  bindings:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.os == 'ubuntu-latest' && 'fedora:38' || null }}

    name: "🐍 Build Bindings on ${{ matrix.os }}"

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🖥️ Setup Environment
        uses: ./.github/actions/setup
        with:
          container: ${{ matrix.os }}
          install-vtk: false

      - name: 🦥 Cache Dependencies
        uses: actions/cache@v3
        with:
          key: python-${{ matrix.os }}
          path: build

      - name: 🐍 Build and check Python Module (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          python3 -m venv venv
          ./venv/Scripts/activate.bat
          pip install .
          python3 -c "import viennals2d; print(viennals2d.__doc__)"

      - name: 🐍 Build and check Python Module (Other)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          python3 -m venv venv
          ./venv/bin/pip install .
          ./venv/bin/python -c "import viennals2d; print(viennals2d.__doc__)"

      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Pre-Built (${{ matrix.os }})
          path: venv
